#Auto generated by FuseSoC
project new anvyl_picorv32
project set family spartan6
project set device xc6slx45
project set package csg484
project set speed -3
project set "Generate Detailed MAP Report" true
project set "Verilog Include Directories" "../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog|../rtl/mor1kx/rtl/verilog|../rtl/components/verilog_utils_0/|../rtl/components/wb_common_1.0/|../rtl/include|../rtl/wishbone" -process "Synthesize - XST"
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_wb_biu.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_status_reg.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_jsp_biu.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_module.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/syncflop.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_crc32.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_jsp_module.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_top.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/bytefifo.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_biu.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_defines.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/syncreg.v
xfile add ../rtl/components/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_wb_module.v
xfile add ../rtl/components/diila/rtl/verilog/diila.v
xfile add ../rtl/components/gpio_0/gpio.v
xfile add ../rtl/components/jtag_tap/tap/rtl/verilog/tap_top.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_branch_prediction.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_bus_if_avalon.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_bus_if_wb32.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_cache_lru.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_cfgrs.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_cpu_cappuccino.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_cpu_espresso.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_cpu_prontoespresso.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_cpu.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_ctrl_cappuccino.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_ctrl_espresso.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_ctrl_prontoespresso.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_dcache.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_decode_execute_cappuccino.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_decode.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_dmmu.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_execute_alu.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_fetch_cappuccino.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_fetch_espresso.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_fetch_prontoespresso.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_icache.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_immu.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_lsu_cappuccino.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_lsu_espresso.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_pic.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_rf_cappuccino.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_rf_espresso.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_simple_dpram_sclk.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_store_buffer.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_ticktimer.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_true_dpram_sclk.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_wb_mux_cappuccino.v
xfile add ../rtl/mor1kx/rtl/verilog/mor1kx_wb_mux_espresso.v
xfile add ../rtl/components/simple_spi/rtl/verilog/fifo4.v
xfile add ../rtl/components/simple_spi/rtl/verilog/simple_spi_top.v
xfile add ../rtl/components/uart16550/rtl/verilog/raminfr.v
xfile add ../rtl/components/uart16550/rtl/verilog/uart_debug_if.v
xfile add ../rtl/components/uart16550/rtl/verilog/uart_receiver.v
xfile add ../rtl/components/uart16550/rtl/verilog/uart_regs.v
xfile add ../rtl/components/uart16550/rtl/verilog/uart_rfifo.v
xfile add ../rtl/components/uart16550/rtl/verilog/uart_sync_flops.v
xfile add ../rtl/components/uart16550/rtl/verilog/uart_tfifo.v
xfile add ../rtl/components/uart16550/rtl/verilog/uart_top.v
xfile add ../rtl/components/uart16550/rtl/verilog/uart_transmitter.v
xfile add ../rtl/components/uart16550/rtl/verilog/uart_wb.v
xfile add ../rtl/components/verilog-arbiter/src/arbiter.v
xfile add ../rtl/components/wb_intercon_1.0/rtl/verilog/wb_arbiter.v
xfile add ../rtl/components/wb_intercon_1.0/rtl/verilog/wb_data_resize.v
xfile add ../rtl/components/wb_intercon_1.0/rtl/verilog/wb_upsizer.v
xfile add ../rtl/components/wb_intercon_1.0/rtl/verilog/wb_mux.v
xfile add ../rtl/anvyl_picorv32.v
xfile add ../rtl/components/clkgen.v
xfile add ../rtl/components/rom.v
xfile add ../rtl/wishbone/wb_intercon.v
xfile add ../rtl/components/xilinx_ddr2/ddr2_mig.v
xfile add ../rtl/components/xilinx_ddr2/infrastructure.v
xfile add ../rtl/components/xilinx_ddr2/iodrp_controller.v
xfile add ../rtl/components/xilinx_ddr2/iodrp_mcb_controller.v
xfile add ../rtl/components/xilinx_ddr2/mcb_raw_wrapper.v
xfile add ../rtl/components/xilinx_ddr2/mcb_soft_calibration_top.v
xfile add ../rtl/components/xilinx_ddr2/mcb_soft_calibration.v
xfile add ../rtl/components/xilinx_ddr2/mcb_ui_top.v
xfile add ../rtl/components/xilinx_ddr2/memc_wrapper.v
xfile add ../rtl/components/xilinx_ddr2/xilinx_ddr2_if.v
xfile add ../rtl/components/xilinx_ddr2/xilinx_ddr2.v
xfile add ../board/anvyl.ucf
project set top "anvyl_picorv32"

process run "Generate Programming File"
